# Generated by Django 6.0.1 on 2026-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Imagen Principal')),
                ('image_tablet', models.ImageField(blank=True, null=True, upload_to='projects/images/tablet/', verbose_name='Imagen Tablet')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='projects/images/mobile/', verbose_name='Imagen Móvil')),
                ('url_site', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('url_repository', models.URLField(blank=True, null=True, verbose_name='Repositorio GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='Tecnologías')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
