# Generated by Django 6.0.1 on 2026-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0002_alter_skill_options_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Desktop image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/mobile/', verbose_name='Mobile image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/tablet/', verbose_name='Tablet image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_repository',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_site',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
