# Generated by Django 6.0.1 on 2026-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_description_and_more'),
        ('skills', '0003_alter_skill_order_alter_skill_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_desktop',
            field=models.ImageField(default='', upload_to='projects/images/desktop/', verbose_name='Desktop Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/mobile/', verbose_name='Mobile Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/tablet/', verbose_name='Tablet Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='Tech Stack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_repository',
            field=models.URLField(blank=True, null=True, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_site',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
    ]
