# Generated by Django 6.0.1 on 2026-01-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image_project_image_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, help_text='Ej: img/icons/cj.svg', max_length=255, null=True, verbose_name='Static Path (Button Icon)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_desktop',
            field=models.CharField(max_length=255, verbose_name='Static Path (Desktop)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Static Path (Mobile)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_tablet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Static Path (Tablet)'),
        ),
    ]
