# Generated by Django 6.0.1 on 2026-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='skills/images/', verbose_name='Logo')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión (Opcional)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['order', 'name'],
            },
        ),
    ]
