# Generated by Django 6.0.1 on 2026-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order of appearance'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Version (Optional)'),
        ),
    ]
