# Generated by Django 6.0.1 on 2026-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Version'),
        ),
    ]
