# Generated by Django 6.0.1 on 2026-01-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_order_alter_skill_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.CharField(max_length=255, verbose_name='Static Path (Logo)'),
        ),
    ]
